name: Integrity

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt-check:
    name: Rustfmt Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install `nightly` toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt
          override: true

      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install `nightly` toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: clippy
          override: true

      - name: Restore cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings -A unused

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install `nightly` toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: llvm-tools-preview
          override: true

      - name: Restore cache
        uses: Swatinem/rust-cache@v2

      - name: Install Tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-tarpaulin
        continue-on-error: true # This command "fails" if the tool is already installed, but we don't care

      - name: Test & Generate Coverage
        run: >
          cargo tarpaulin
          --all-features
          --no-fail-fast
          --ignore-tests
          --ignore-panics
          --exclude-files build.rs
          --workspace
          --timeout 120
          --out Html
          --out Xml

      - name: Upload HTML Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: Coverage Report
          path: tarpaulin-report.html
          if-no-files-found: error

      - name: Upload Codecov Coverage Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS
          fail_ci_if_error: true
          directory: ./
          files: cobertura.xml
          verbose: true

  misplaced-use-statements-check:
    name: Misplaced `use` Statements Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install `nightly` toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Restore cache
        uses: Swatinem/rust-cache@v2

      - name: Install Ripgrep
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: ripgrep

      # This uses some Regex to find `use` statements that are above the `// Uses` header
      # This is an issue with how Rustfmt handles comments above `use` statements and there's not much that can be done
      # For future reference, the reason for the `./` at the end is here: https://github.com/BurntSushi/ripgrep/issues/2181
      - name: Check For Misplaced `use` Statements
        run: >
          ! rg
          --multiline
          --multiline-dotall
          --case-sensitive
          --type rust
          '^use .+^// Uses$'
          ./
